### ISSUE TITLE
Table parse error

### ISSUE THREAD

**Issue by DigitalFeonix** [softwaretechnik-berlin/dbml-renderer#12]
If you are following the DBML docs about using [un-supported settings](https://www.dbml.org/docs/#column-settings) and put the column type in quotes, the parser fails.

test.dbml
```
Table galleries {
  gallery_id "int(3) unsigned zerofill" [pk, not null, increment]
  title varchar(255) [not null]
  comment text [not null]
}
```

```shell
> dbml-renderer -i test.dbml -o test.svg
Could not parse input at line 2. Expected ":" or [a-zA-Z_()0-9,] but "\"" found.
```

Testing on [dbdiagram.io](https://dbdiagram.io/d) shows expected output.

![image](https://user-images.githubusercontent.com/197201/154547918-5a8bfc0f-c917-4c87-9cb9-7e9318b21579.png)

**Comment by barnardb** [comment]
Thanks for reporting. The example you've given in this issue has been added as a test case, and it's been fixed in v1.0.20.
