### ISSUE TITLE
Install v1.0.20 from npm doesn't include all file updates 

### ISSUE THREAD

**Issue by DigitalFeonix** [softwaretechnik-berlin/dbml-renderer#14]
After upgrading with `npm upgrade -g @softwaretechnik/dbml-renderer` and failing to see the fixes for #11, #12, and #13 I did a fresh install by running `npm remove -g @softwaretechnik/dbml-renderer` followed by `npm install -g  @softwaretechnik/dbml-renderer`.

I confirmed again that I had the proper version.

```shell
C:\dev\open-source\dbml-test>dbml-renderer --version
1.0.20
```

Looking through what was installed in my global `node_modules` folder and the repo found it seems that ba6cd9a5773072d73542d557b2ff8fb312d778cf was the last commit that was included as part of v1.0.20

**Comment by DigitalFeonix** [comment]
I was temporarily able to work around this by using npm's ability to [install](https://docs.npmjs.com/cli/v8/commands/npm-install) directly from Github with `npm install -g softwaretechnik-berlin/dbml-renderer#c431ba6d86a04ce23bcd68fbcbfa745408086b5d`

**Comment by barnardb** [comment]
Thanks for the report. I seem to have botched that release. It should work with v1.0.21.
