### ISSUE TITLE
Could not parse input at line 65:15. Expected "{", [a-zA-Z0-9_], or whitespace but "." found

### ISSUE THREAD

**Issue by carun** [softwaretechnik-berlin/dbml-renderer#26]
I tried the advanced example from https://dbdiagram.io/d

![image](https://github.com/softwaretechnik-berlin/dbml-renderer/assets/471374/3987d216-dbb2-4178-82c4-306f3c64bc2d)

```console
c:\> dbml-renderer -i 'sample.txt' -o out.png
Could not parse input at line 65:15. Expected "{", [a-zA-Z0-9_], or whitespace but "." found.
c:\>
```

See attached, in case dbdiagrams.io changes the sample: [sample.txt](https://github.com/softwaretechnik-berlin/dbml-renderer/files/12221765/sample.txt)

**Comment by rolivares** [comment]
same here, problems is about declaring enums types

![image](https://github.com/softwaretechnik-berlin/dbml-renderer/assets/348077/0ba799cc-07e0-4e8e-8de8-df7516ff3d90)
