### ISSUE TITLE
Error using decimal(10,2)

### ISSUE THREAD

**Issue by danilort** [softwaretechnik-berlin/dbml-renderer#29]
If I use the data_type decima(10,2), I get error:

`Could not parse input at line 5:22. Expected ")" or [a-zA-Z0-9_] but "," found.`

# file 4.dbml

```
Table utenti {
    id int [pk, increment]
    nome varchar     
    data_creato timestamp
    numero decimal(10,2)
    nazione_id int
}

```
![immagine](https://github.com/softwaretechnik-berlin/dbml-renderer/assets/16148184/45efe07e-535f-45bd-8911-cf914f5dfb4a)

**Comment by andyyou** [comment]
+1

**Comment by momoca** [comment]
+1

**Comment by giacomomasseron** [comment]
+1

**Comment by mathi1652** [comment]
Any workaround for this issue ?
