### ISSUE TITLE
Update docs with how to use on a website

### ISSUE THREAD

**Issue by timvink** [softwaretechnik-berlin/dbml-renderer#3]
Hi @lucastorri @fleipold 

Cool package! Kudos on the hard work put in.

I'm a javascript n00b, so using this package on a website is not straightforward for me:
- F.e. I tried to find a CDN for a (preferably minified) version of the `.js` file for this package. I tried some different URLs like *https://unpkg.com/browse/softwaretechnik/dbml-renderer/index.js* but failed, and I can't figure out which file I need to use on https://www.jsdelivr.com/package/npm/@softwaretechnik/dbml-renderer.
- The next step is how to use the exposed functions, for which I'll have to dive into the javascript code.

Perhaps you would be willing to update the docs for me to describe this? Specifically, a guide [like this one from mermaid](https://mermaid-js.github.io/mermaid/#/n00b-gettingStarted?id=this-is-what-needs-to-go-into-the-html-file-and-all-of-them-are-important-for-the-mermaidapi-to-render-the-diagrams) would help me out a lot!

Context: I'm looking into building a plugin to render dbml diagrams in mkdocs. Kinda of like how mermaid.js is supported: https://squidfunk.github.io/mkdocs-material/reference/diagrams/

**Comment by lucastorri** [comment]
Hi @timvink, I have to admit that online usage wasn't initially thought and therefore never tested.

I do believe that it should be possible ATM, and that improvements to this use case should come in future versions. 

To perhaps unblock you, I'll write down, from the top of my head, what I believe would be necessary:

In a npm/yarn-based project, do:

```bash
npm i @softwaretechnik/dbml-renderer
```

In your source code:

```javascript
// import the render function
import dbmlRenderer from "@softwaretechnik/dbml-renderer";

// your DBML definition
const dbmlSource = `...`;

// render the DBML definition to a SVG document
const svgContent = dbmlRenderer(dbmlSource, "svg");

// add the SVG to the page
document.getElementById("my-container").innerHTML = svgContent;
```

Again, the code above is untested, but it should give you some light on the matter.

**Comment by timvink** [comment]
Thanks for the pointers! I'm a python dev so quite new to the `npm` world.

I ran the commands and got
>  'Uncaught TypeError: Failed to resolve module specifier "@softwaretechnik/dbml-renderer". Relative references must start with either "/", "./", or "../".'

I googled some more, added `<script type='module'>`, followed [this guide](https://hackernoon.com/use-es6-javascript-syntax-require-import-etc-in-your-front-end-project-5eefcef745c2) to try and `browserify` the script using ES6, but got a

> Error: Plugin/Preset files are not allowed to export objects, only functions. 

To be honest, I have no idea what I'm doing 🙈 

Could you help with creating a `dmblRenderer.min.js` file? Not sure if that's a lot of work though? Btw, holistics might release something similar (see https://github.com/holistics/dbml/issues/156). 

I'm quite certain that once I have a 'plain' javascript file I can use that to build a `mkdocs-dmbl-plugin` on top of `dmbl-renderer`.

**Comment by barnardb** [comment]
Note that dbml-renderer creates a graphviz visualisation and depends on @aduh95/viz.js to render it, so I'm not sure a single JS file with just the dbml-renderer code in it would meet your needs. It looks like this was more of a support request around the module loader you were using. I hope you were able to resolve the issue. I'm going to close this ticket.
